# RECOMMENDING RESTAURANTS USING CONTENT BASED RECOMMENDATION SYSTEM

### IN THIS PROJECT WE WILL RECOMMEND RESTAURANTS TO THE USERS BASED ON THEIR INPUTS AND THEIR CHOICE OF CUISINE

In [61]:
import pandas as pd
import numpy as np

In [62]:
Restaurant = pd.read_excel('Restaurants.xlsx')
Restaurant = Restaurant.drop('Links',axis = 1)
Restaurant.head()

Restaurant Names Ratings                                Cuisine  \
0        MS Bakery & Sweets     4.3     Bakery, Desserts, Fast Food, Pizza   
1                Iqbal Cafe     4.4                    Hyderabadi, Biryani   
2   Mahalaxmi Tiffin Centre     4.1                           South Indian   
3  Al- Naseer Tahari Centre     4.3                                Biryani   
4                 Pizza Hut     3.7  Pizza, Fast Food, Desserts, Beverages   

   Price for one  
0            150  
1            150  
2            150  
3            150  
4            150

In [63]:
user_inp = pd.read_excel('User_inp.xlsx')
user_inp = user_inp.drop('Links',axis = 1)
user_inp

Restaurant Names  Ratings  \
0                   Sahara Bakers      3.7   
1                             KFC      3.9   
2             Subbaiah Gari Hotel      4.1   
3                Paradise Biryani      3.9   
4              Pista House Bakery      4.3   
5  Shah Ghouse Hotel & Restaurant      4.0   
6                   Swagath Hotel      4.2   
7                   Just Parantha      4.2   
8                          Mehfil      4.1   
9                     Cream Stone      4.3   

                                             Cuisine  Price for one  
0            Chinese, Bakery, Sichuan, Pizza, Burger            100  
1    Burger, Fast Food, Biryani, Desserts, Beverages            100  
2                       South Indian, Andhra, Mithai            100  
3                Biryani, Kebab, Desserts, Beverages            100  
4  Fast Food, Sandwich, Pizza, Burger, Wraps, Rol...            100  
5  North Indian, Chinese, Mughlai, Mandi, Sichuan...            100  
6                South Indian, Chinese, North Indian            100  
7                                       North Indian            100  
8                     North Indian, Biryani, Mughlai            100  
9                                Ice Cream, Desserts            150

In [64]:
Restaurant.describe(include='all').T

count unique  \
Restaurant Names    647    626   
Ratings           647.0   24.0   
Cuisine             647    388   
Price for one     647.0    NaN   

                                                              top   freq  \
Restaurant Names  Kwality Wall痴 Frozen Dessert and Ice Cream Shop      3   
Ratings                                                       4.0  102.0   
Cuisine                                              South Indian     67   
Price for one                                                 NaN    NaN   

                        mean        std   min    25%    50%    75%    max  
Restaurant Names         NaN        NaN   NaN    NaN    NaN    NaN    NaN  
Ratings                  NaN        NaN   NaN    NaN    NaN    NaN    NaN  
Cuisine                  NaN        NaN   NaN    NaN    NaN    NaN    NaN  
Price for one     170.401855  97.576639  50.0  100.0  150.0  250.0  400.0

In [65]:
user_inp.describe(include='all').T

count unique                                      top freq  \
Restaurant Names    10     10                            Sahara Bakers    1   
Ratings           10.0    NaN                                      NaN  NaN   
Cuisine             10     10  Chinese, Bakery, Sichuan, Pizza, Burger    1   
Price for one     10.0    NaN                                      NaN  NaN   

                   mean        std    min    25%    50%    75%    max  
Restaurant Names    NaN        NaN    NaN    NaN    NaN    NaN    NaN  
Ratings            4.07   0.194651    3.7  3.925    4.1    4.2    4.3  
Cuisine             NaN        NaN    NaN    NaN    NaN    NaN    NaN  
Price for one     105.0  15.811388  100.0  100.0  100.0  100.0  150.0

In [66]:
Restaurant['Ratings'] = Restaurant['Ratings'].replace('New','0').replace('-','0').astype('float')
Restaurant.Ratings.unique()

array([4.3, 4.4, 4.1, 3.7, 4.2, 4. , 3.9, 4.5, 3.8, 4.6, 3.6, 0. , 3.4,
       3.5, 3.1, 3.3, 2.7, 3.2, 3. , 4.7, 2.8, 2.9, 2.6])

In [67]:
user_inp['Ratings'] = user_inp['Ratings'].replace('New','0').replace('-','0').astype('float')
user_inp.Ratings.unique()

array([3.7, 3.9, 4.1, 4.3, 4. , 4.2])

In [68]:
X = Restaurant[['Restaurant Names','Ratings','Cuisine']]
XX = X
X.head()

Restaurant Names  Ratings                                Cuisine
0        MS Bakery & Sweets      4.3     Bakery, Desserts, Fast Food, Pizza
1                Iqbal Cafe      4.4                    Hyderabadi, Biryani
2   Mahalaxmi Tiffin Centre      4.1                           South Indian
3  Al- Naseer Tahari Centre      4.3                                Biryani
4                 Pizza Hut      3.7  Pizza, Fast Food, Desserts, Beverages

In [69]:
Y = user_inp[['Restaurant Names','Ratings','Cuisine']]
YY = Y
Y.head()

Restaurant Names  Ratings  \
0        Sahara Bakers      3.7   
1                  KFC      3.9   
2  Subbaiah Gari Hotel      4.1   
3     Paradise Biryani      3.9   
4   Pista House Bakery      4.3   

                                             Cuisine  
0            Chinese, Bakery, Sichuan, Pizza, Burger  
1    Burger, Fast Food, Biryani, Desserts, Beverages  
2                       South Indian, Andhra, Mithai  
3                Biryani, Kebab, Desserts, Beverages  
4  Fast Food, Sandwich, Pizza, Burger, Wraps, Rol...

In [70]:
X['Cuisine'] = X.Cuisine.str.split(',')
Y['Cuisine'] = Y.Cuisine.str.split(',')

C:\Users\chira\AppData\Local\Temp/ipykernel_16900/2196222832.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Cuisine'] = X.Cuisine.str.split(',')
C:\Users\chira\AppData\Local\Temp/ipykernel_16900/2196222832.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y['Cuisine'] = Y.Cuisine.str.split(',')


In [71]:
XX = X.copy()

try:
    for index, row in X.iterrows():
        for cuisine in row['Cuisine']:
            XX.at[index, cuisine] = 1
except:
    print('')

XX = XX.fillna(0)
XX.head()

Restaurant Names  Ratings  \
0        MS Bakery & Sweets      4.3   
1                Iqbal Cafe      4.4   
2   Mahalaxmi Tiffin Centre      4.1   
3  Al- Naseer Tahari Centre      4.3   
4                 Pizza Hut      3.7   

                                      Cuisine  Bakery   Desserts   Fast Food  \
0     [Bakery,  Desserts,  Fast Food,  Pizza]     1.0        1.0         1.0   
1                      [Hyderabadi,  Biryani]     0.0        0.0         0.0   
2                              [South Indian]     0.0        0.0         0.0   
3                                   [Biryani]     0.0        0.0         0.0   
4  [Pizza,  Fast Food,  Desserts,  Beverages]     0.0        1.0         1.0   

    Pizza  Hyderabadi   Biryani  South Indian  ...  Paan  Wraps  Sandwich  \
0     1.0         0.0       0.0           0.0  ...   0.0    0.0       0.0   
1     0.0         1.0       1.0           0.0  ...   0.0    0.0       0.0   
2     0.0         0.0       0.0           1.0  ...   0.0    0.0       0.0   
3     0.0         0.0       0.0           0.0  ...   0.0    0.0       0.0   
4     0.0         0.0       0.0           0.0  ...   0.0    0.0       0.0   

    Bubble Tea  Continental  Frozen Yogurt   European   Oriental  \
0          0.0          0.0            0.0        0.0        0.0   
1          0.0          0.0            0.0        0.0        0.0   
2          0.0          0.0            0.0        0.0        0.0   
3          0.0          0.0            0.0        0.0        0.0   
4          0.0          0.0            0.0        0.0        0.0   

   Middle Eastern  Seafood  
0             0.0      0.0  
1             0.0      0.0  
2             0.0      0.0  
3             0.0      0.0  
4             0.0      0.0  

[5 rows x 99 columns]

In [72]:
YY = Y.copy()

try:
    for index, row in Y.iterrows():
        for cuisine in row['Cuisine']:
            YY.at[index, cuisine] = 1
except:
    print('')

YY = YY.fillna(0)
YY.head()

Restaurant Names  Ratings  \
0        Sahara Bakers      3.7   
1                  KFC      3.9   
2  Subbaiah Gari Hotel      4.1   
3     Paradise Biryani      3.9   
4   Pista House Bakery      4.3   

                                             Cuisine  Chinese   Bakery  \
0      [Chinese,  Bakery,  Sichuan,  Pizza,  Burger]      1.0      1.0   
1  [Burger,  Fast Food,  Biryani,  Desserts,  Bev...      0.0      0.0   
2                   [South Indian,  Andhra,  Mithai]      0.0      0.0   
3           [Biryani,  Kebab,  Desserts,  Beverages]      0.0      0.0   
4  [Fast Food,  Sandwich,  Pizza,  Burger,  Wraps...      0.0      0.0   

    Sichuan   Pizza   Burger  Burger   Fast Food  ...   Rolls   Salad  \
0       1.0     1.0      1.0     0.0         0.0  ...     0.0     0.0   
1       0.0     0.0      0.0     1.0         1.0  ...     0.0     0.0   
2       0.0     0.0      0.0     0.0         0.0  ...     0.0     0.0   
3       0.0     0.0      0.0     0.0         0.0  ...     0.0     0.0   
4       0.0     1.0      1.0     0.0         0.0  ...     1.0     1.0   

   North Indian   Chinese   Mughlai   Mandi   Shawarma   Seafood  \
0           0.0       0.0       0.0     0.0        0.0       0.0   
1           0.0       0.0       0.0     0.0        0.0       0.0   
2           0.0       0.0       0.0     0.0        0.0       0.0   
3           0.0       0.0       0.0     0.0        0.0       0.0   
4           0.0       0.0       0.0     0.0        0.0       0.0   

    North Indian  Ice Cream  
0            0.0        0.0  
1            0.0        0.0  
2            0.0        0.0  
3            0.0        0.0  
4            0.0        0.0  

[5 rows x 31 columns]

## We will extract cuisines and ratings of the restaurants into 2 different dataframes

We are selecting specific cuisines given by users as inputs.

In [73]:
cuis = XX.drop('Restaurant Names',axis = 1).drop('Ratings',axis = 1).drop('Cuisine',axis = 1)
cuisine = cuis[['Chinese', ' Bakery', ' Sichuan', ' Pizza', ' Burger', 'Burger',
       ' Fast Food', ' Biryani', ' Desserts', ' Beverages', 'South Indian',
       ' Andhra', ' Mithai', 'Biryani', ' Kebab', 'Fast Food', ' Sandwich',
       ' Wraps', ' Rolls', ' Salad', 'North Indian', ' Chinese', ' Mughlai',
       ' Mandi', ' Shawarma', ' Seafood', ' North Indian', 'Ice Cream']]
print(cuisine.shape)
cuisine.head()

(647, 28)


Chinese   Bakery   Sichuan   Pizza   Burger  Burger   Fast Food   Biryani  \
0      0.0      0.0       0.0     1.0      0.0     0.0         1.0       0.0   
1      0.0      0.0       0.0     0.0      0.0     0.0         0.0       1.0   
2      0.0      0.0       0.0     0.0      0.0     0.0         0.0       0.0   
3      0.0      0.0       0.0     0.0      0.0     0.0         0.0       0.0   
4      0.0      0.0       0.0     0.0      0.0     0.0         1.0       0.0   

    Desserts   Beverages  ...   Rolls   Salad  North Indian   Chinese  \
0        1.0         0.0  ...     0.0     0.0           0.0       0.0   
1        0.0         0.0  ...     0.0     0.0           0.0       0.0   
2        0.0         0.0  ...     0.0     0.0           0.0       0.0   
3        0.0         0.0  ...     0.0     0.0           0.0       0.0   
4        1.0         1.0  ...     0.0     0.0           0.0       0.0   

    Mughlai   Mandi   Shawarma   Seafood   North Indian  Ice Cream  
0       0.0     0.0        0.0       0.0            0.0        0.0  
1       0.0     0.0        0.0       0.0            0.0        0.0  
2       0.0     0.0        0.0       0.0            0.0        0.0  
3       0.0     0.0        0.0       0.0            0.0        0.0  
4       0.0     0.0        0.0       0.0            0.0        0.0  

[5 rows x 28 columns]

In [74]:
ratings = XX[['Ratings']]
ratings.head()

Ratings
0      4.3
1      4.4
2      4.1
3      4.3
4      3.7

In [75]:
user_cuisine = YY.drop('Restaurant Names',axis = 1).drop('Ratings',axis = 1).drop('Cuisine',axis = 1)
print('USER INPUTS : Cuisines rows and columns : ',user_cuisine.shape)
user_cuisine.head()

USER INPUTS : Cuisines rows and columns :  (10, 28)


Chinese   Bakery   Sichuan   Pizza   Burger  Burger   Fast Food   Biryani  \
0      1.0      1.0       1.0     1.0      1.0     0.0         0.0       0.0   
1      0.0      0.0       0.0     0.0      0.0     1.0         1.0       1.0   
2      0.0      0.0       0.0     0.0      0.0     0.0         0.0       0.0   
3      0.0      0.0       0.0     0.0      0.0     0.0         0.0       0.0   
4      0.0      0.0       0.0     1.0      1.0     0.0         0.0       0.0   

    Desserts   Beverages  ...   Rolls   Salad  North Indian   Chinese  \
0        0.0         0.0  ...     0.0     0.0           0.0       0.0   
1        1.0         1.0  ...     0.0     0.0           0.0       0.0   
2        0.0         0.0  ...     0.0     0.0           0.0       0.0   
3        1.0         1.0  ...     0.0     0.0           0.0       0.0   
4        1.0         0.0  ...     1.0     1.0           0.0       0.0   

    Mughlai   Mandi   Shawarma   Seafood   North Indian  Ice Cream  
0       0.0     0.0        0.0       0.0            0.0        0.0  
1       0.0     0.0        0.0       0.0            0.0        0.0  
2       0.0     0.0        0.0       0.0            0.0        0.0  
3       0.0     0.0        0.0       0.0            0.0        0.0  
4       0.0     0.0        0.0       0.0            0.0        0.0  

[5 rows x 28 columns]

In [76]:
user_cuisine.columns

Index(['Chinese', ' Bakery', ' Sichuan', ' Pizza', ' Burger', 'Burger',
       ' Fast Food', ' Biryani', ' Desserts', ' Beverages', 'South Indian',
       ' Andhra', ' Mithai', 'Biryani', ' Kebab', 'Fast Food', ' Sandwich',
       ' Wraps', ' Rolls', ' Salad', 'North Indian', ' Chinese', ' Mughlai',
       ' Mandi', ' Shawarma', ' Seafood', ' North Indian', 'Ice Cream'],
      dtype='object')

In [77]:
user_ratings = YY[['Ratings']]
user_ratings.head()

Ratings
0      3.7
1      3.9
2      4.1
3      3.9
4      4.3

## We have collected all the possible data : 
### cuisine, ratings, user_cuisine, user_ratings

# CONTENT BASED RECOMMENDATION SYSTEM

STEP 1 : LETS BUILD A USER PROFILE

a - user_ratings * user_cuisine <br>
b - Compute weighted matrix by finding the sum of each columns (ex : sum of entire North Indian column)

A USER PROFILE IS BUILT : user_profile

In [78]:
user_r = user_ratings.to_numpy()
user_c = user_cuisine.to_numpy()
print(user_r.shape, user_c.shape)

(10, 1) (10, 28)


In [79]:
rc = user_r * user_c
rc[:1]

array([[3.7, 3.7, 3.7, 3.7, 3.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
        0. , 0. ]])

In [80]:
weighted_matrix = rc.sum(axis=0)
print(weighted_matrix)
print(weighted_matrix.shape)
user_profile = weighted_matrix

[ 3.7  3.7  7.7  8.   8.   3.9  3.9  8.  16.4 11.8  8.3  4.1  4.1  3.9
  3.9  4.3  4.3  4.3  4.3  4.3 12.3  8.2  8.1  4.   4.   4.   4.2  4.3]
(28,)


STEP 2 : WE HAVE TO MULTIPLY USER PROFILE WITH THE CUISINE DATA.

a - user_profile * cuisines<br>
b - Compute weighted matrix by finding the sum of each rows (ex : sum of entire (Pizza Hut) restauant row )

In [81]:
cuisines = cuisine.to_numpy()
cuisines[:1]

array([[0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
recommend = user_profile * cuisines
recommend[:1]

array([[ 0. ,  0. ,  0. ,  8. ,  0. ,  0. ,  3.9,  0. , 16.4,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [83]:
weighted_avg_recommend = recommend.sum(axis = 1)
weighted_avg_recommend.shape

(647,)

In [84]:
final = pd.DataFrame(weighted_avg_recommend)
final = final.rename(columns = {0:'Recommended ratings of restaurants for Users based on User profile'})
X['Recommended ratings of restaurants for Users based on User profile'] = final

In [86]:
sorted_X = X.sort_values(by='Recommended ratings of restaurants for Users based on User profile',ascending = False)

In [87]:
sorted_X

Restaurant Names  Ratings  \
197                Hotel Abinand Grand      3.1   
33    Capital Multi Cuisine Restaurant      3.9   
616  Hydrate The Bar - Hampshire Plaza      0.0   
193   Black Pearl - Hotel Central Park      3.9   
108                       Hotel Sohail      4.2   
..                                 ...      ...   
430                        Shahi Zaiqa      3.8   
435            Mohammedi Confectioners      4.1   
440                 Sri Krishna Sweets      4.7   
444                          Cocoworks      3.9   
388          Iceberg Organic Icecreams      3.8   

                                               Cuisine  \
197  [North Indian,  Chinese,  Mughlai,  Seafood,  ...   
33   [North Indian,  Chinese,  Biryani,  Seafood,  ...   
616  [North Indian,  Chinese,  Beverages,  Biryani,...   
193  [North Indian,  Chinese,  Mughlai,  Seafood,  ...   
108  [North Indian,  Mughlai,  Kebab,  Chinese,  Be...   
..                                                 ...   
430                                       [Hyderabadi]   
435                                           [Mithai]   
440                                           [Mithai]   
444                                        [Beverages]   
388                             [Desserts,  Ice Cream]   

     Recommended ratings of restaurants for Users based on User profile  
197                                               72.9                   
33                                                68.6                   
616                                               64.4                   
193                                               64.0                   
108                                               60.7                   
..                                                 ...                   
430                                                0.0                   
435                                                0.0                   
440                                                0.0                   
444                                                0.0                   
388                                                0.0                   

[647 rows x 4 columns]

## Hotel Abhinandan Grand is the top Recommended Restaurant based on User Profile